-- Rebuild change_log with named constraints and a vocabulary that fits.
--
-- This is the last opportunity to change this table's shape, and that is the
-- whole reason it happens now rather than later.
--
-- docs/AUDIT.md rule 10 makes change_log append-only: no UPDATE, no DELETE,
-- ever. That rule also removes every ordinary route to altering it. The
-- add-column / copy / drop-column / rename dance used on service_instance.source
-- in 00008 is unavailable here, because its second step is literally
-- `UPDATE change_log`. A full rebuild is the only remaining option, and after
-- POC sign-off a rebuild of the audit table is exactly the act the append-only
-- guarantee exists to forbid.
--
-- So: recorded deliberately, done once, pre-sign-off, and every row is carried
-- across verbatim by the INSERT ... SELECT below. No row is edited, dropped, or
-- reordered. docs/DECISIONS.md records the decision.
--
-- Two things are being fixed.
--
-- 1. The action vocabulary is already too narrow, and its CHECK is inline and
--    unnamed, so on SQLite it can never be widened -- a named CHECK added
--    alongside it does not help, because both must pass. AUDIT.md rule 10
--    already documents the cost being paid: the retention prune records itself
--    as `delete` because `prune` could not be added. Verifying a dependency
--    logs as `update`; clearing a health override logs as `update`. Each is a
--    distinct operator act flattened into a word that does not describe it.
--
-- 2. The table has no constraints beyond NOT NULL, and NOT NULL does not stop
--    an empty string. All of these are accepted by the schema as it stands:
--    entity_type='', entity_id='', actor='', diff='not json', at='yesterday'.
--    The permanent record of who changed what is the last table that should
--    take a malformed row, and `health_override` two migrations later already
--    uses the `<> ''` idiom -- it simply was not applied here.
--
-- Every constraint below is NAMED. On SQLite an unnamed inline constraint
-- cannot be dropped (`ALTER TABLE ... DROP CONSTRAINT` reports `no such
-- constraint` for the autogenerated name), which is what made this rebuild
-- necessary in the first place. Naming them costs nothing and means the next
-- change to this table is an ALTER rather than a rebuild.
--
-- Portable as written: nothing in the schema references change_log, so the
-- drop-and-rename needs no foreign key juggling on either engine.

-- +goose Up
CREATE TABLE change_log_new (
  id          TEXT NOT NULL PRIMARY KEY,
  entity_type TEXT NOT NULL CONSTRAINT change_log_entity_type_check CHECK (entity_type <> ''),
  entity_id   TEXT NOT NULL CONSTRAINT change_log_entity_id_check   CHECK (entity_id <> ''),
  -- verify: a person attesting an edge is legitimate (dependency.verified_by).
  -- clear:  an operator ending a health override before it lapses.
  -- prune:  the retention job, which rule 10 requires to record itself.
  -- import: reserved for a bulk load, so the first one does not need this again.
  action      TEXT NOT NULL CONSTRAINT change_log_action_check
                CHECK (action IN ('create','update','delete','retire',
                                  'verify','clear','prune','import')),
  -- An opaque app_user.id, never a username or an email: the trail carries no
  -- personal data, so it can be kept indefinitely and scrubbing an account
  -- answers an erasure request while the log keeps its integrity.
  actor       TEXT NOT NULL CONSTRAINT change_log_actor_check CHECK (actor <> ''),
  actor_kind  TEXT NOT NULL CONSTRAINT change_log_actor_kind_check
                CHECK (actor_kind IN ('user','agent','system')),
  diff        TEXT NOT NULL CONSTRAINT change_log_diff_check CHECK (diff <> ''),
  ticket_ref  TEXT,
  -- RFC3339 UTC to the second, which domain.FormatTime always produces, so
  -- every value is exactly 20 characters. LIKE with `_` behaves identically on
  -- both engines and catches a timestamp written in some other shape, which
  -- would otherwise sort wrongly forever in a table ordered by this column.
  at          TEXT NOT NULL CONSTRAINT change_log_at_check
                CHECK (at LIKE '____-__-__T__:__:__Z')
);

INSERT INTO change_log_new (id, entity_type, entity_id, action, actor, actor_kind, diff, ticket_ref, at)
SELECT id, entity_type, entity_id, action, actor, actor_kind, diff, ticket_ref, at
FROM change_log;

DROP TABLE change_log;
ALTER TABLE change_log_new RENAME TO change_log;

CREATE INDEX idx_changelog_entity ON change_log(entity_type, entity_id, at);
CREATE INDEX idx_changelog_at ON change_log(at);

-- +goose Down
CREATE TABLE change_log_old (
  id          TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id   TEXT NOT NULL,
  action      TEXT NOT NULL CHECK (action IN ('create','update','delete','retire')),
  actor       TEXT NOT NULL,
  actor_kind  TEXT NOT NULL CHECK (actor_kind IN ('user','agent','system')),
  diff        TEXT NOT NULL,
  ticket_ref  TEXT,
  at          TEXT NOT NULL
);

-- Rows written with one of the new action values cannot exist in the old shape.
-- They are dropped rather than rewritten: inventing a different action for them
-- would put a false statement in the audit trail, which is worse than a down
-- migration that loses rows it warned about. A down migration is a development
-- convenience here, not a supported production path.
INSERT INTO change_log_old (id, entity_type, entity_id, action, actor, actor_kind, diff, ticket_ref, at)
SELECT id, entity_type, entity_id, action, actor, actor_kind, diff, ticket_ref, at
FROM change_log
WHERE action IN ('create','update','delete','retire');

DROP TABLE change_log;
ALTER TABLE change_log_old RENAME TO change_log;

CREATE INDEX idx_changelog_entity ON change_log(entity_type, entity_id, at);
CREATE INDEX idx_changelog_at ON change_log(at);
