// invctl — infrastructure inventory
// Copyright (C) 2026 Madalin Ignisca <hi@madalin.me>
//
// Licensed under the GNU Affero General Public License, version 3 only —
// no later version applies. See LICENSE for the full text.
//
// SPDX-License-Identifier: AGPL-3.0-only

package web_test

import (
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// THE STRAND LIMIT LIVES IN THREE PLACES AND NOTHING HELD THEM TOGETHER.
//
// The breakout form renders a FIXED set of strand pickers, because
// TestAlpineDirectivesAreCSPSafe scans template SOURCE and forbids any Go
// template action inside an x-show/x-on/x-bind attribute -- so the rows cannot
// be generated by a {{range}}. That is the right constraint and it has a cost:
// the count is written out literally in the template, again in app.js as
// show0..showN/disabledN getters, and a third time as breakoutMaxStrands in Go.
//
// Raising the Go constant alone gives an operator strand pickers that render
// and do nothing, because the Alpine component has no getter for them. Adding a
// template row alone gives a picker Alpine never shows. Neither fails anything.
// It was flagged as a known hand-sync by the implementer; a known hand-sync
// with no test is the same thing as an unknown one, six months later.
//
// This is the cheapest possible guard: all three say the same number, or this
// fails naming which one drifted.
func TestTheBreakoutStrandLimitAgreesEverywhere(t *testing.T) {
	root := repoRoot(t)

	goConst := countMatches(t, filepath.Join(root, "internal", "web", "handlers", "forms.go"),
		regexp.MustCompile(`breakoutMaxStrands\s*=\s*(\d+)`), true)
	if goConst == 0 {
		t.Fatal("breakoutMaxStrands not found in internal/web/handlers/forms.go. The scan " +
			"has stopped matching the source, which reads as agreement and is not.")
	}

	jsGetters := countDistinct(t, filepath.Join(root, "web", "static", "app.js"),
		regexp.MustCompile(`show(\d+)\b`))
	tmplRows := countDistinct(t, filepath.Join(root, "web", "templates", "partials", "forms.html"),
		regexp.MustCompile(`disabled(\d+)\b`))

	if jsGetters != goConst {
		t.Errorf("breakoutMaxStrands is %d but app.js declares %d show<N> getters.\n"+
			"    A picker with no getter renders and does nothing: the operator sees a "+
			"strand row, fills it, and it never becomes a strand. Nothing errors.",
			goConst, jsGetters)
	}
	if tmplRows != goConst {
		t.Errorf("breakoutMaxStrands is %d but partials/forms.html has %d disabled<N> rows.\n"+
			"    A getter with no row is dead JS; a row past the constant is a picker the "+
			"handler will never read.", goConst, tmplRows)
	}
}

// countMatches returns the numeric value of the first submatch, or the number
// of matches when value is false.
func countMatches(t *testing.T, path string, re *regexp.Regexp, value bool) int {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	m := re.FindSubmatch(raw)
	if m == nil {
		return 0
	}
	if !value {
		return len(re.FindAllSubmatch(raw, -1))
	}
	n := 0
	for _, c := range m[1] {
		n = n*10 + int(c-'0')
	}
	return n
}

// countDistinct counts distinct numeric suffixes, so a getter mentioned twice
// is still one strand.
func countDistinct(t *testing.T, path string, re *regexp.Regexp) int {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	seen := map[string]bool{}
	for _, m := range re.FindAllSubmatch(raw, -1) {
		seen[string(m[1])] = true
	}
	return len(seen)
}
