// invctl — infrastructure inventory
// Copyright (C) 2026 Madalin Ignisca <hi@madalin.me>
//
// Licensed under the GNU Affero General Public License, version 3 only —
// no later version applies. See LICENSE for the full text.
//
// SPDX-License-Identifier: AGPL-3.0-only

// Package license holds the guard that keeps the copyright notice on every
// source file. It has no runtime code: the licence is a property of the tree,
// not of anything that runs.
package license

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// identifier is what every source file must carry. The SPDX line is the
// machine-readable half; the human-readable notice sits above it and in
// LICENSE.
const identifier = "SPDX-License-Identifier: AGPL-3.0-only"

// carriesANotice are the extensions whose files are ours to license.
var carriesANotice = map[string]bool{
	".go": true, ".sql": true, ".html": true, ".css": true, ".js": true,
}

// exempt is every file that must NOT carry our notice, with the reason.
//
// Vendored code belongs to somebody else and claiming it would be false;
// generated output is rewritten by its generator on the next build and carries
// its own notice already.
var exempt = map[string]string{
	"web/static/htmx.min.js":   "vendored, third party",
	"web/static/alpine.min.js": "vendored, third party",
	"web/static/app.css":       "generated by Tailwind, carries its own notice",
}

// A file added without the notice is a file whose copyright is unstated, and
// the omission is invisible in review — nobody reads the top of a diff for
// something that is the same in every other file. So it is a test.
func TestEverySourceFileCarriesTheLicence(t *testing.T) {
	root := repoRoot(t)
	// The only variable is root, which repoRoot derived by walking up from the
	// test's own working directory to the go.mod above it. Nothing here comes
	// from a request, a flag or an environment variable.
	//nolint:gosec // G204: fixed argv; the single variable is the repository root
	out, err := exec.Command("git", "-C", root, "ls-files").Output()
	if err != nil {
		t.Fatalf("listing tracked files: %v", err)
	}

	var checked int
	for _, path := range strings.Fields(string(out)) {
		if reason, ok := exempt[path]; ok {
			// Assert the exemption is still true rather than trusting the
			// list: a vendored file that became ours would sit here forever.
			if strings.Contains(read(t, root, path), identifier) {
				t.Errorf("%s carries our notice but is exempt as %s", path, reason)
			}
			continue
		}
		if !carriesANotice[filepath.Ext(path)] {
			continue
		}
		checked++
		if !strings.Contains(read(t, root, path), identifier) {
			t.Errorf("%s has no %s", path, identifier)
		}
	}
	if checked == 0 {
		t.Fatal("no files were checked; this test is asserting nothing")
	}
	t.Logf("%d source files carry the licence", checked)
}

// The full text ships with the code, because the notice in each file points at
// it and a pointer to a missing file is not a licence.
func TestTheLicenceTextShips(t *testing.T) {
	body := read(t, repoRoot(t), "LICENSE")
	for _, want := range []string{
		"GNU AFFERO GENERAL PUBLIC LICENSE",
		"Version 3, 19 November 2007",
		// The clause the whole choice of AGPL rests on: running a modified
		// version over a network obliges you to offer the source.
		"13. Remote Network Interaction",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("LICENSE does not contain %q", want)
		}
	}
}

func read(t *testing.T, root, path string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(root, path))
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return string(body)
}

func repoRoot(t *testing.T) string {
	t.Helper()
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		t.Fatalf("finding the repo root: %v", err)
	}
	return strings.TrimSpace(string(out))
}
