-- invctl — infrastructure inventory
-- Copyright (C) 2026 Madalin Ignisca <hi@madalin.me>
--
-- Licensed under the GNU Affero General Public License, version 3 only —
-- no later version applies. See LICENSE for the full text.
--
-- SPDX-License-Identifier: AGPL-3.0-only

-- service_instance gains a lifecycle, and its uniqueness stops counting
-- withdrawn placements. PostgreSQL half; see migrations/sqlite/00002 for the
-- defect this fixes and why it cannot wait until after sign-off.
--
-- The same end state, reached without a rebuild: PostgreSQL names its
-- constraints, so the UNIQUE can simply be dropped. The name below is the
-- server's own autogenerated one, read from pg_constraint rather than guessed
-- -- it is derived from the table and column names, so it is stable for a
-- constraint declared inline as UNIQUE (service_id, host_asset_id, ordinal).
--
-- Because no table is dropped, the six ON DELETE CASCADE dependents
-- (rt_systemd, rt_windows, rt_container, rt_k8s, dependency) are untouched and
-- none of the foreign key juggling the SQLite half needs applies here.

-- +goose Up
ALTER TABLE service_instance
  DROP CONSTRAINT service_instance_service_id_host_asset_id_ordinal_key;

ALTER TABLE service_instance
  ADD COLUMN lifecycle TEXT NOT NULL DEFAULT 'active'
    CONSTRAINT service_instance_lifecycle_check CHECK (lifecycle IN ('active','retired'));

-- desired_state = 'disabled' meant "withdrawn" at the time it was written.
-- Matches the CASE in the SQLite half exactly; both engines must land on the
-- same data or the suite's dual-engine runs would diverge here.
UPDATE service_instance SET lifecycle = 'retired' WHERE desired_state = 'disabled';

-- Named to match the SQLite half, so a reader comparing the two engines sees
-- one schema rather than two that happen to agree.
ALTER TABLE service_instance
  ADD CONSTRAINT service_instance_ordinal_check CHECK (ordinal >= 0);

CREATE UNIQUE INDEX idx_instance_placement_active
  ON service_instance(service_id, host_asset_id, ordinal) WHERE lifecycle = 'active';

-- +goose Down
DROP INDEX IF EXISTS idx_instance_placement_active;

ALTER TABLE service_instance
  DROP CONSTRAINT IF EXISTS service_instance_ordinal_check;

-- A retired placement whose slot has since been reused would violate the
-- restored UNIQUE, so it goes. Same trade as the SQLite half and for the same
-- reason: a down migration is a development convenience, not a supported
-- production path.
DELETE FROM service_instance WHERE lifecycle = 'retired';

ALTER TABLE service_instance DROP COLUMN lifecycle;

ALTER TABLE service_instance
  ADD CONSTRAINT service_instance_service_id_host_asset_id_ordinal_key
  UNIQUE (service_id, host_asset_id, ordinal);
