-- service_instance gains a lifecycle, and its uniqueness stops counting
-- withdrawn placements.
--
-- THE DEFECT. A placement is withdrawn today by writing
-- desired_state = 'disabled', and DisableInstance logs that as ActionRetire --
-- the code already means "this placement is gone" and is putting it in the
-- intent column, because there was nowhere else. Two facts are then stuck in
-- one column: desired_state is DECLARED INTENT ("should this be running"),
-- while "is this placement still part of the estate" is a lifecycle. AUDIT.md
-- is explicit that intent-collapse is what makes drift undetectable.
--
-- The visible consequence is that the withdrawn row keeps its slot in
-- UNIQUE (service_id, host_asset_id, ordinal), so re-recording that service on
-- that host at that ordinal fails. Reproduced through the store API on both
-- engines: CreateInstance returns domain.ErrConflict, which the handler renders
-- as a 422 against a field the operator cannot do anything about. A rebuilt VM
-- can never be recorded where it was.
--
-- WHY THIS CANNOT WAIT. The UNIQUE is an unnamed inline constraint, and SQLite
-- cannot drop one -- ALTER TABLE ... DROP CONSTRAINT reports `no such
-- constraint` for the autogenerated name (measured against the pinned driver,
-- modernc.org/sqlite v1.54.0, SQLite 3.53.3). The only route is a table
-- rebuild, and after POC sign-off a destructive migration needs an explicitly
-- recorded decision. Every comparable table already has this shape:
-- net_group_member, net_uplink, net_attachment and health_override all pair a
-- lifecycle with a partial unique index. This table was simply missed.
--
-- WHY NO TRANSACTION. Six tables reference service_instance ON DELETE CASCADE
-- (rt_systemd, rt_windows, rt_container, rt_k8s and dependency), so DROP TABLE
-- with foreign keys enforced silently takes their rows with it -- measured: 16
-- rt_* rows vanished. The pragma that turns enforcement off is a no-op inside a
-- transaction, and goose wraps each migration in one by default. Hence the
-- directive. The cost is that a failure part-way leaves the database
-- half-migrated; acceptable for a fixture pre-sign-off, and the reason this is
-- happening now rather than against real data.
--
-- Constraints are NAMED, unlike the ones being replaced, so the next change to
-- this table is an ALTER rather than another rebuild.

-- +goose NO TRANSACTION

-- +goose Up
PRAGMA foreign_keys = OFF;

CREATE TABLE service_instance_new (
  id             TEXT NOT NULL PRIMARY KEY,
  service_id     TEXT NOT NULL REFERENCES service(id) ON DELETE CASCADE,
  host_asset_id  TEXT NOT NULL REFERENCES asset(id),
  runtime_type   TEXT NOT NULL CONSTRAINT service_instance_runtime_type_check
                   CHECK (runtime_type IN
                     ('systemd','windows_service','container','k8s_workload','appliance')),
  role           TEXT,
  shard          TEXT,
  ordinal        INTEGER NOT NULL DEFAULT 0
                   CONSTRAINT service_instance_ordinal_check CHECK (ordinal >= 0),
  -- Intent: what this placement is supposed to be doing. Unchanged.
  desired_state  TEXT NOT NULL DEFAULT 'running'
                   CONSTRAINT service_instance_desired_state_check
                   CHECK (desired_state IN ('running','stopped','disabled')),
  -- Existence: whether this placement is still part of the estate. The soft
  -- delete every other entity table already has.
  lifecycle      TEXT NOT NULL DEFAULT 'active'
                   CONSTRAINT service_instance_lifecycle_check
                   CHECK (lifecycle IN ('active','retired')),
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  source         TEXT NOT NULL DEFAULT 'declared'
                   CONSTRAINT service_instance_source_check
                   CHECK (source IN
                     ('declared','discovered_systemd','discovered_k8s','discovered_config'))
  -- No inline UNIQUE. See the partial index below.
);

-- desired_state = 'disabled' meant "withdrawn" at the time it was written, so
-- that is what it becomes. Nothing is lost: the column keeps its value too, and
-- the change_log entry that produced it is untouched.
INSERT INTO service_instance_new
  (id, service_id, host_asset_id, runtime_type, role, shard, ordinal,
   desired_state, lifecycle, created_at, updated_at, source)
SELECT id, service_id, host_asset_id, runtime_type, role, shard, ordinal,
       desired_state,
       CASE WHEN desired_state = 'disabled' THEN 'retired' ELSE 'active' END,
       created_at, updated_at, source
FROM service_instance;

DROP TABLE service_instance;
ALTER TABLE service_instance_new RENAME TO service_instance;

-- Uniqueness over LIVE placements only. A withdrawn one no longer reserves the
-- slot, so the same service can be recorded on that host again.
CREATE UNIQUE INDEX idx_instance_placement_active
  ON service_instance(service_id, host_asset_id, ordinal) WHERE lifecycle = 'active';
CREATE INDEX idx_instance_service ON service_instance(service_id);
CREATE INDEX idx_instance_host ON service_instance(host_asset_id);

-- No PRAGMA foreign_key_check here. It reads like a safety net and is not one:
-- goose runs migration statements with Exec, the pragma reports violations as
-- result rows, and Exec discards them -- so it finds the problem, throws it
-- away and reports success. store.verifyForeignKeys runs the same check with
-- Query after every migration instead, where a violation can actually fail the
-- run.
PRAGMA foreign_keys = ON;

-- +goose Down
PRAGMA foreign_keys = OFF;

CREATE TABLE service_instance_old (
  id             TEXT PRIMARY KEY,
  service_id     TEXT NOT NULL REFERENCES service(id) ON DELETE CASCADE,
  host_asset_id  TEXT NOT NULL REFERENCES asset(id),
  runtime_type   TEXT NOT NULL CHECK (runtime_type IN
                   ('systemd','windows_service','container','k8s_workload','appliance')),
  role           TEXT,
  shard          TEXT,
  ordinal        INTEGER NOT NULL DEFAULT 0,
  desired_state  TEXT NOT NULL DEFAULT 'running'
                   CHECK (desired_state IN ('running','stopped','disabled')),
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  source         TEXT NOT NULL DEFAULT 'declared'
                   CHECK (source IN
                     ('declared','discovered_systemd','discovered_k8s','discovered_config')),
  UNIQUE (service_id, host_asset_id, ordinal)
);

-- A retired placement whose slot has since been reused cannot exist in the old
-- shape, so the retired row is dropped rather than the live one. Losing the
-- withdrawn record is the lesser harm, and it is announced here rather than
-- discovered as a UNIQUE violation mid-migration.
INSERT INTO service_instance_old
  (id, service_id, host_asset_id, runtime_type, role, shard, ordinal,
   desired_state, created_at, updated_at, source)
SELECT id, service_id, host_asset_id, runtime_type, role, shard, ordinal,
       desired_state, created_at, updated_at, source
FROM service_instance
WHERE lifecycle = 'active';

DROP TABLE service_instance;
ALTER TABLE service_instance_old RENAME TO service_instance;

CREATE INDEX idx_instance_service ON service_instance(service_id);
CREATE INDEX idx_instance_host ON service_instance(host_asset_id);

PRAGMA foreign_keys = ON;
